---
title: Manu Rosales - Músico, compositor, productor y docente
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  styles:
    title: Styles
    output: true
  uploads:
    title: Uploads
    output: true
description: Con una visión contemporánea de la composición, Manu Rosales crea un
  universo ecléctico de canciones. Su guitarra evoca distintas raíces del mundo, desde
  el folklore de Argentina, pasando por los Andes y Brasil y llegando al Noroeste
  de África
baseurl: 
url: https://manurosales.com
footer: 2022 — MANUROSALES.COM
